from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(810, 530)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setFocusPolicy(QtCore.Qt.NoFocus)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(10, 10, 791, 491))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.widget.setFont(font)
        self.widget.setObjectName("widget")
        self.sort3 = QtWidgets.QComboBox(self.widget)
        self.sort3.setGeometry(QtCore.QRect(10, 10, 381, 24))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sort3.sizePolicy().hasHeightForWidth())
        self.sort3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.sort3.setFont(font)
        self.sort3.setObjectName("sort3")
        self.sort3.addItem("")
        self.sort3.addItem("")
        self.sort3.addItem("")
        self.sort3.addItem("")
        self.listCinema = QtWidgets.QListWidget(self.widget)
        self.listCinema.setGeometry(QtCore.QRect(10, 46, 491, 431))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listCinema.sizePolicy().hasHeightForWidth())
        self.listCinema.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.listCinema.setFont(font)
        self.listCinema.setObjectName("listCinema")
        self.update_sort = QtWidgets.QPushButton(self.widget)
        self.update_sort.setGeometry(QtCore.QRect(400, 10, 101, 26))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.update_sort.sizePolicy().hasHeightForWidth())
        self.update_sort.setSizePolicy(sizePolicy)
        self.update_sort.setObjectName("update_sort")
        self.layoutWidget = QtWidgets.QWidget(self.widget)
        self.layoutWidget.setGeometry(QtCore.QRect(513, 10, 271, 471))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.nameCinema = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nameCinema.sizePolicy().hasHeightForWidth())
        self.nameCinema.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.nameCinema.setFont(font)
        self.nameCinema.setObjectName("nameCinema")
        self.verticalLayout.addWidget(self.nameCinema)
        self.genre = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.genre.sizePolicy().hasHeightForWidth())
        self.genre.setSizePolicy(sizePolicy)
        self.genre.setObjectName("genre")
        self.verticalLayout.addWidget(self.genre)
        self.year = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.year.sizePolicy().hasHeightForWidth())
        self.year.setSizePolicy(sizePolicy)
        self.year.setObjectName("year")
        self.verticalLayout.addWidget(self.year)
        self.description = QtWidgets.QPlainTextEdit(self.layoutWidget)
        self.description.setObjectName("description")
        self.verticalLayout.addWidget(self.description)
        self.button_create = QtWidgets.QPushButton(self.layoutWidget)
        self.button_create.setObjectName("button_create")
        self.verticalLayout.addWidget(self.button_create)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.button_edit = QtWidgets.QPushButton(self.layoutWidget)
        self.button_edit.setObjectName("button_edit")
        self.horizontalLayout.addWidget(self.button_edit)
        self.button_delete = QtWidgets.QPushButton(self.layoutWidget)
        self.button_delete.setObjectName("button_delete")
        self.horizontalLayout.addWidget(self.button_delete)
        self.verticalLayout.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 810, 21))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.support = QtWidgets.QMenu(self.menubar)
        self.support.setObjectName("support")
        MainWindow.setMenuBar(self.menubar)
        self.addCinema = QtWidgets.QAction(MainWindow)
        self.addCinema.setCheckable(True)
        self.addCinema.setShortcutContext(QtCore.Qt.WindowShortcut)
        self.addCinema.setObjectName("addCinema")
        self.deleteCinema = QtWidgets.QAction(MainWindow)
        self.deleteCinema.setObjectName("deleteCinema")
        self.editCinema = QtWidgets.QAction(MainWindow)
        self.editCinema.setObjectName("editCinema")
        self.about_programm = QtWidgets.QAction(MainWindow)
        self.about_programm.setObjectName("about_programm")
        self.menu.addAction(self.addCinema)
        self.menu.addAction(self.deleteCinema)
        self.menu.addAction(self.editCinema)
        self.support.addAction(self.about_programm)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.support.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Кинотека"))
        self.sort3.setItemText(0, _translate("MainWindow", "по А-Я"))
        self.sort3.setItemText(1, _translate("MainWindow", "по Я-А"))
        self.sort3.setItemText(2, _translate("MainWindow", "по жанру"))
        self.sort3.setItemText(3, _translate("MainWindow", "по году"))
        self.update_sort.setText(_translate("MainWindow", "Обновить"))
        self.nameCinema.setText(_translate("MainWindow", "Название Кино"))
        self.genre.setText(_translate("MainWindow", "Жанр и т.д."))
        self.year.setText(_translate("MainWindow", "Год"))
        self.button_create.setText(_translate("MainWindow", "Добавить"))
        self.button_edit.setText(_translate("MainWindow", "Изменить"))
        self.button_delete.setText(_translate("MainWindow", "Удалить"))
        self.menu.setTitle(_translate("MainWindow", "Кино"))
        self.support.setTitle(_translate("MainWindow", "Помощь"))
        self.addCinema.setText(_translate("MainWindow", "Добавить кино"))
        self.addCinema.setShortcut(_translate("MainWindow", "Ctrl+A"))
        self.deleteCinema.setText(_translate("MainWindow", "Удалить кино"))
        self.deleteCinema.setShortcut(_translate("MainWindow", "Ctrl+D"))
        self.editCinema.setText(_translate("MainWindow", "Редактировать кино"))
        self.editCinema.setShortcut(_translate("MainWindow", "Ctrl+E"))
        self.about_programm.setText(_translate("MainWindow", "О программе"))
        self.about_programm.setShortcut(_translate("MainWindow", "Ctrl+H"))
